import React, { useState } from 'react'
import { BookOpen, Download, Eye, EyeOff, ChevronDown, ChevronUp } from 'lucide-react'
import useBookStore from '../hooks/useBookStore'

const BookPreview = () => {
  const { bookData, generatedChapters, chapterOutlines } = useBookStore()
  const [expandedChapters, setExpandedChapters] = useState({})
  const [showAll, setShowAll] = useState(true)

  if (generatedChapters.length === 0) {
    return null
  }

  const toggleChapter = (index) => {
    setExpandedChapters(prev => ({
      ...prev,
      [index]: !prev[index]
    }))
  }

  const toggleAll = () => {
    if (showAll) {
      setExpandedChapters({})
    } else {
      const allExpanded = {}
      generatedChapters.forEach((_, i) => {
        allExpanded[i] = true
      })
      setExpandedChapters(allExpanded)
    }
    setShowAll(!showAll)
  }

  const handleDownload = () => {
    const bookContent = generateBookText()
    const blob = new Blob([bookContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${bookData.title.replace(/[^a-z0-9]/gi, '_')}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const generateBookText = () => {
    let text = ''
    
    // Title Page
    text += '═'.repeat(60) + '\n'
    text += '\n'
    text += `${bookData.title.toUpperCase()}\n`
    text += '\n'
    text += `Genre: ${bookData.genre}\n`
    text += `Tone: ${bookData.tone}\n`
    text += '\n'
    text += '═'.repeat(60) + '\n\n'

    // Table of Contents
    text += 'TABLE OF CONTENTS\n'
    text += '─'.repeat(30) + '\n\n'
    chapterOutlines.forEach((chapter, i) => {
      text += `Chapter ${i + 1}: ${chapter.title}\n`
    })
    text += '\n' + '═'.repeat(60) + '\n\n'

    // Chapters
    generatedChapters.forEach((chapter, i) => {
      text += `CHAPTER ${i + 1}\n`
      text += `${chapter.title}\n`
      text += '─'.repeat(40) + '\n\n'
      text += chapter.content + '\n\n'
      text += '═'.repeat(60) + '\n\n'
    })

    // Footer
    text += '\n'
    text += 'THE END\n'
    text += '\n'
    text += `Generated by BookWrightPro\n`
    text += `${new Date().toLocaleDateString()}\n`

    return text
  }

  const wordCount = generatedChapters.reduce((total, chapter) => {
    return total + chapter.content.split(/\s+/).length
  }, 0)

  return (
    <div className="card" style={styles.container}>
      <div className="card-header">
        <div style={styles.headerTitle}>
          <BookOpen size={20} color="var(--accent-secondary)" />
          <h3>Generated Book</h3>
        </div>
        <div style={styles.headerActions}>
          <button
            className="btn-secondary"
            onClick={toggleAll}
            style={styles.toggleBtn}
          >
            {showAll ? <EyeOff size={16} /> : <Eye size={16} />}
            {showAll ? 'Collapse All' : 'Expand All'}
          </button>
          <button
            className="btn-primary"
            onClick={handleDownload}
            style={styles.downloadBtn}
          >
            <Download size={16} />
            Download .txt
          </button>
        </div>
      </div>

      {/* Stats */}
      <div style={styles.stats}>
        <div style={styles.stat}>
          <span style={styles.statValue}>{generatedChapters.length}</span>
          <span style={styles.statLabel}>Chapters</span>
        </div>
        <div style={styles.stat}>
          <span style={styles.statValue}>{wordCount.toLocaleString()}</span>
          <span style={styles.statLabel}>Words</span>
        </div>
        <div style={styles.stat}>
          <span style={styles.statValue}>{Math.ceil(wordCount / 250)}</span>
          <span style={styles.statLabel}>Est. Pages</span>
        </div>
      </div>

      {/* Book Title */}
      <div style={styles.bookTitle}>
        <h2>{bookData.title}</h2>
        <p className="text-muted">{bookData.genre} • {bookData.tone}</p>
      </div>

      {/* Chapters */}
      <div style={styles.chapterList}>
        {generatedChapters.map((chapter, index) => (
          <div key={index} style={styles.chapterCard}>
            <div 
              style={styles.chapterHeader}
              onClick={() => toggleChapter(index)}
            >
              <div style={styles.chapterInfo}>
                <span style={styles.chapterNumber}>Chapter {index + 1}</span>
                <h4 style={styles.chapterTitle}>{chapter.title}</h4>
              </div>
              <div style={styles.chapterMeta}>
                <span className="text-xs text-muted">
                  {chapter.content.split(/\s+/).length} words
                </span>
                {expandedChapters[index] ? (
                  <ChevronUp size={20} color="var(--text-muted)" />
                ) : (
                  <ChevronDown size={20} color="var(--text-muted)" />
                )}
              </div>
            </div>
            
            {expandedChapters[index] && (
              <div style={styles.chapterContent}>
                {chapter.content.split('\n\n').map((paragraph, i) => (
                  <p key={i} style={styles.paragraph}>{paragraph}</p>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}

const styles = {
  container: {
    marginTop: '1.5rem',
  },
  headerTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  headerActions: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap',
  },
  toggleBtn: {
    padding: '0.5rem 0.75rem',
    fontSize: '0.75rem',
  },
  downloadBtn: {
    padding: '0.5rem 1rem',
    fontSize: '0.875rem',
  },
  stats: {
    display: 'flex',
    gap: '2rem',
    padding: '1rem',
    backgroundColor: 'var(--bg-tertiary)',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  stat: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.25rem',
  },
  statValue: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: 'var(--accent-secondary)',
  },
  statLabel: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  bookTitle: {
    textAlign: 'center',
    marginBottom: '1.5rem',
    paddingBottom: '1.5rem',
    borderBottom: '1px solid var(--border-primary)',
  },
  chapterList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  chapterCard: {
    backgroundColor: 'var(--bg-tertiary)',
    borderRadius: '8px',
    border: '1px solid var(--border-primary)',
    overflow: 'hidden',
  },
  chapterHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1rem',
    cursor: 'pointer',
    transition: 'background-color var(--transition-fast)',
  },
  chapterInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  chapterNumber: {
    fontSize: '0.7rem',
    fontWeight: 600,
    color: 'var(--accent-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  chapterTitle: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  chapterMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  chapterContent: {
    padding: '0 1.5rem 1.5rem',
    borderTop: '1px solid var(--border-primary)',
    backgroundColor: 'var(--bg-secondary)',
  },
  paragraph: {
    marginTop: '1rem',
    lineHeight: 1.8,
    color: 'var(--text-secondary)',
    textAlign: 'justify',
    textIndent: '2rem',
    fontFamily: "'Merriweather', Georgia, serif",
    fontSize: '0.95rem',
  },
}

export default BookPreview
